version: '3.8'

services:
  vk-script:
    build:
      context: ./TrueTabsHackVkExt
      dockerfile: Dockerfile
    container_name: vk-script
    restart: unless-stopped
    env_file:
      - ./TrueTabsHackVkExt/.env
    volumes:
      - ./TrueTabsHackVkExt:/app

  telegram-bot:
    build:
      context: ./TgExt
      dockerfile: Dockerfile
    container_name: telegram-bot
    restart: unless-stopped
    env_file:
      - ./TgExt/.env

  triggers:
    build:
      context: ./triggers
      dockerfile: Dockerfile
    container_name: triggers
    restart: unless-stopped
